version: 2.1
orbs:
  slim-scanner: slimdevops/slim-scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5
parameters:
  image-name:
    description: Image to be scanned.
    type: string
    default: node:latest #Name of the image to be scanned eg:node
  image-connector:
    description: Connector.
    type: string
    default: dockerhub.public #Connector used by slim to get the image eg:dockerhub.public
  cimg-tag:
    description: Which tag to be used for cimg/base.
    type: string
    default: current #Which tag to be used for cimg eg:  cimg/base:current
filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:<< pipeline.parameters.cimg-tag >>

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - slim-scanner/vscan:
          filters: *filters
          imageName: << pipeline.parameters.image-name >>
          imageConnector: << pipeline.parameters.image-connector >>
          cimgTag: << pipeline.parameters.cimg-tag >>
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: slimdevops/slim-scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - slim-scanner/vscan
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
